project:
  type: website

website:
  title: "website"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
    - text: "In-class Ex03"
      menu:
        - href: "In-class_ex03/In-class_ex03.html"
          text: "In-class_Exercise"
        
        
    right:
      - href: index.qmd
        text: Home
      - about.qmd
   

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

