project:
  type: website

website:
  title: "My VAA Journey"
  navbar:
    left:
    - text: "In-class Exercise"
      menu:
        - href: "In-class_EX/In-class_Ex03.html"
          text: "In-class_Exercise 3"
        - href: "In-class_EX/In-class_Ex04/In-class_Ex04.html"
          text: "In-class_Exercise 4"
    - text: "Take-home Exercise"
      menu:
        - href: "Take-home_EX/Take-home_Ex1.html"
          text: "Take-home Exercise 1"
    - text: "Hands-on Exercise"
      menu:
        - href: "Hands-on_EX/Hands-on_Ex1.html"
          text: "Hands-on Exercise 1"
        
    right:
      - href: index.qmd
        text: Home
      - about.qmd
   

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

