project:
  type: website

website:
  title: "My VAA Journey"
  navbar:
    left:
    - text: "In-class Exercise"
      menu:
        - href: "In-class_EX/In-class_Ex03.html"
          text: "In-class_Exercise 3"
        - href: "In-class_EX/In-class_Ex04/In-class_Ex04.html"
          text: "In-class_Exercise 4"
        - href: "In-class_EX/In-class_Ex05/In-class_Ex05.html"
          text: "In-class_Exercise 5"
        - href: "In-class_EX/In-class_Ex06/In-class_Ex06.html"
          text: "In-class_Exercise 6"
        - href: "In-class_EX/In-class_Ex07/In-class_Ex07.html"
          text: "In-class_Exercise 7"
        - href: "In-class_EX/In-class_Ex08/In-class_Ex08.html"
          text: "In-class_Exercise 8"
        - href: "In-class_EX/In-class_Ex09/In-class_Ex09.html"
          text: "In-class_Exercise 9"
        - href: "In-class_EX/In-class_Ex10/In-class_Ex10.html"
          text: "In-class_Exercise 10"
    - text: "Take-home Exercise"
      menu:
        - href: "Take-home_EX/Take-home_Ex1.html"
          text: "Take-home Exercise 1"
        - href: "Take-home_EX/Take-home_EX02/Take-home_Ex2.html"
          text: "Take-home Exercise 2"
        - href: "Take-home_EX/Take-home_Ex3.html"
          text: "Take-home Exercise 3"
    - text: "Hands-on Exercise"
      menu:
        - href: "Hands-on_EX/Hands-on_Ex1.html"
          text: "Hands-on Exercise 1"
        
    right:
      - href: index.qmd
        text: Home
      - about.qmd
   

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

