project:
  type: website

website:
  title: "website"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text:"Hands-on Exercise 1"
        
        
    right:
      - href: index.qmd
        text: Home
      - about.qmd
   

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

